namespace CustomerService.Domain.Entities;

/// <summary>
/// Channel through which a notification is delivered. The demo only persists
/// in-app notifications; Email/SMS are reserved for a future sender.
/// </summary>
public enum NotificationChannel
{
    /// <summary>In-app bell / notification center.</summary>
    InApp = 0,

    /// <summary>Email (reserved — not sent in the demo).</summary>
    Email = 1,

    /// <summary>SMS (reserved — not sent in the demo).</summary>
    Sms = 2,
}

/// <summary>
/// Lifecycle state of a notification.
/// </summary>
public enum NotificationStatus
{
    /// <summary>Created but not yet delivered.</summary>
    Unread = 0,

    /// <summary>Seen by the user in the notification center.</summary>
    Read = 1,
}

/// <summary>
/// Why a <see cref="Notification"/> was generated. Used as part of the
/// de-duplication key (CaseId, Channel, Type) so that, for example, an
/// overdue-agent email and a resolved-customer email for the same case on the
/// same Email channel are treated as distinct and both can be sent.
/// </summary>
public enum NotificationType
{
    /// <summary>Overdue follow-up reminder (agent-facing).</summary>
    CaseOverdue = 0,

    /// <summary>Case resolved/closed confirmation (customer-facing).</summary>
    CaseResolved = 1,

    /// <summary>Customer portal invite (customer-facing).</summary>
    CustomerInvite = 2,
}

/// <summary>
/// A notification generated by the system (e.g. an overdue follow-up alert).
/// Persisted so it can be shown in the in-app notification center; the
/// <see cref="Channel"/> and <see cref="Type"/> are recorded so outbound
/// Email/SMS senders can de-duplicate correctly.
/// </summary>
public class Notification
{
    /// <summary>Primary key.</summary>
    public int Id { get; set; }

    /// <summary>Short title (e.g. "Overdue follow-up").</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Longer message body.</summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>Delivery channel (InApp in the demo).</summary>
    public NotificationChannel Channel { get; set; } = NotificationChannel.InApp;

    /// <summary>Read/unread state.</summary>
    public NotificationStatus Status { get; set; } = NotificationStatus.Unread;

    /// <summary>
    /// Why this notification was generated (overdue reminder, resolved
    /// confirmation, etc.). Part of the de-duplication key so distinct
    /// notification types for the same case/channel are not collapsed.
    /// </summary>
    public NotificationType Type { get; set; } = NotificationType.CaseOverdue;

    /// <summary>UTC timestamp the notification was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Optional link target so the UI can deep-link to the related entity.
    /// Stored as a route path (e.g. "/cases/6").
    /// </summary>
    public string? Link { get; set; }

    /// <summary>Foreign key to the related case, when applicable.</summary>
    public int? CaseId { get; set; }

    /// <summary>
    /// Recipient address for outbound channels (Email address or phone
    /// number). Null for InApp notifications, which are shown in the bell.
    /// </summary>
    public string? Recipient { get; set; }
}
